version: 2
jobs:
  bhuvan:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "first commit..."
  kishan:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "next commit"
  workflows:
    version: 2
    bhuvan_kishan:
      jobs:
        - bhuvan
        - kishan
        
